version: '3.8'

services:
  bot:
    build:
      context: docker
      dockerfile: docker/Dockerfile
    restart: on-failure
    volumes:
      - "./:/usr/src/app"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "637
